name: 01-📲 Telegram File Downloader

on:
  workflow_dispatch:
    inputs:

      telegram_links:
        description: "🔗 Telegram links"
        required: true
        type: string

      password:
        description: "🔐 Archive password (optional)"
        required: false
        default: ""
        type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  download-telegram:

    name: 📥 Download Telegram Files

    runs-on: ubuntu-24.04

    timeout-minutes: 180

    permissions:
      contents: write

    steps:

      - name: 📂 Checkout repository
        uses: actions/checkout@v5

      - name: 📁 Create folders
        run: |
          mkdir -p downloads
          mkdir -p output

      - name: 📋 Show input
        run: |
          echo "Telegram Links:"
          echo "${{ github.event.inputs.telegram_links }}"

          echo ""
          echo "Password:"
          echo "${{ github.event.inputs.password }}"

      - name: 📥 Fake Download Test
        run: |
          echo "Test file" > downloads/test.txt

      - name: 📦 Create Archive
        run: |

          PASSWORD="${{ github.event.inputs.password }}"

          if [ -z "$PASSWORD" ]; then

            7z a output/result.7z downloads/*

          else

            7z a -p"$PASSWORD" -mhe=on output/result.7z downloads/*

          fi

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: telegram-download
          path: output/result.7z
